export interface GettingStartedWorkflowNodePort {
  acceptedSourceGroups: string[];
  acceptedSourceModelIds: string[];
  key: string;
  label: string;
  multiple: boolean;
  portType: string;
  side: string | null;
}

export interface GettingStartedWorkflowNodeReference {
  commands: GettingStartedWorkflowNodePort[];
  fields: string[];
  group: string;
  id: string;
  inputs: GettingStartedWorkflowNodePort[];
  name: string;
  outputs: GettingStartedWorkflowNodePort[];
  summary: string;
  usage: string;
}

export const GETTING_STARTED_WORKFLOW_NODES: GettingStartedWorkflowNodeReference[] = [
  {
    commands: [],
    fields: ['description', 'model', 'prompt', 'status', 'source', 'timestamp', 'internalNodeLibraryId', 'failureMitigation', 'retryCount'],
    group: 'AI Models',
    id: 'claude',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Claude',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Claude workflow node.',
    usage: 'Use Claude to process runtime input and emit output for downstream nodes.',
  },
  {
    commands: [],
    fields: [
      'description',
      'model',
      'prompt',
      'temperature',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'AI Models',
    id: 'deepseek',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Deepseek',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Deepseek workflow node.',
    usage: 'Use Deepseek to process runtime input and emit output for downstream nodes.',
  },
  {
    commands: [],
    fields: ['description', 'model', 'prompt', 'status', 'source', 'timestamp', 'internalNodeLibraryId', 'failureMitigation', 'retryCount'],
    group: 'AI Models',
    id: 'gemini',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Gemini',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Gemini workflow node.',
    usage: 'Use Gemini to process runtime input and emit output for downstream nodes.',
  },
  {
    commands: [],
    fields: ['description', 'model', 'prompt', 'status', 'source', 'timestamp', 'internalNodeLibraryId', 'failureMitigation', 'retryCount'],
    group: 'AI Models',
    id: 'groq',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Groq',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Groq workflow node.',
    usage: 'Use Groq to process runtime input and emit output for downstream nodes.',
  },
  {
    commands: [],
    fields: [
      'description',
      'model',
      'prompt',
      'temperature',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'AI Models',
    id: 'mistral',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Mistral',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Mistral workflow node.',
    usage: 'Use Mistral to process runtime input and emit output for downstream nodes.',
  },
  {
    commands: [],
    fields: [
      'description',
      'model',
      'prompt',
      'temperature',
      'status',
      'source',
      'timestamp',
      'internalNodeLibraryId',
      'failureMitigation',
      'retryCount',
    ],
    group: 'AI Models',
    id: 'openai',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Openai',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Openai workflow node.',
    usage: 'Use Openai to process runtime input and emit output for downstream nodes.',
  },
  {
    commands: [],
    fields: [
      'description',
      'model',
      'prompt',
      'temperature',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'AI Models',
    id: 'perplexity',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Perplexity',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Perplexity workflow node.',
    usage: 'Use Perplexity to process runtime input and emit output for downstream nodes.',
  },
  {
    commands: [
      {
        acceptedSourceGroups: ['AI Models'],
        acceptedSourceModelIds: ['openai', 'claude', 'gemini', 'groq', 'deepseek', 'perplexity', 'mistral'],
        key: 'llm',
        label: 'LLM',
        multiple: true,
        portType: 'bi-directional',
        side: 'bottom',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'tools',
        label: 'Tools',
        multiple: true,
        portType: 'bi-directional',
        side: 'bottom',
      },
    ],
    fields: [
      'description',
      'planningPrompt',
      'executionMode',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'AI Orchestration',
    id: 'ai-governor',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'Input',
        multiple: true,
        portType: 'generic-input',
        side: 'left',
      },
    ],
    name: 'Ai Governor',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: 'right',
      },
    ],
    summary: 'Worker-first governor node that plans connected LLM/tool actions and can optionally execute them.',
    usage:
      'Use plan-only when a policy node must review the proposed plan. Use execute-plan to run an already approved plan against connected router tools. Use plan-and-run only when the governor should both decide and execute in one step.',
  },
  {
    commands: [],
    fields: [
      'mode',
      'pendingAction',
      'description',
      'limit',
      'offset',
      'plan',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Context',
    id: 'current-chat',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Current Chat',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Worker-owned chat-state node for reusable input, history, context, and pending-plan bundles.',
    usage: 'Choose the bundles you need, then use Pending Action only when you want to store or clear a pending plan.',
  },
  {
    commands: [],
    fields: ['description', 'internalNodeLibraryId', 'status', 'source', 'timestamp', 'failureMitigation', 'retryCount'],
    group: 'Context',
    id: 'current-subjects',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Current Subjects',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Load subjects from `workflow.input.subjectIds` and fallback `workflow.input.postIds` using workflow GraphQL settings.',
    usage:
      'Use Current Subjects to resolve current workflow subjects from workflow input, including post-to-subject fallback lookups, directly in the worker.',
  },
  {
    commands: [],
    fields: ['description', 'status', 'source', 'timestamp', 'payload', 'internalNodeLibraryId', 'failureMitigation', 'retryCount'],
    group: 'Data',
    id: 'code',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: false,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Code',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Runs JavaScript inside the node worker against the current input, node properties, and workflow context.',
    usage:
      'Write JavaScript in the code editor. The worker executes it locally with access to `input`, `properties`, `workflow`, `node`, and `console`.',
  },
  {
    commands: [],
    fields: ['description', 'files', 'status', 'source', 'timestamp', 'internalNodeLibraryId', 'failureMitigation', 'retryCount'],
    group: 'Data',
    id: 'excel',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Excel',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Parse attached CSV files into table rows directly in the worker.',
    usage: 'Attach a CSV file to emit table columns and rows without depending on a backend parser.',
  },
  {
    commands: [],
    fields: ['description', 'files', 'status', 'source', 'timestamp', 'internalNodeLibraryId', 'failureMitigation', 'retryCount'],
    group: 'Data',
    id: 'file',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'File',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Expose attached files for downstream workflow nodes.',
    usage: 'Attach one or more files and pass them through to downstream nodes without calling a backend service.',
  },
  {
    commands: [],
    fields: ['description', 'internalNodeLibraryId', 'status', 'source', 'timestamp', 'failureMitigation', 'retryCount'],
    group: 'Data',
    id: 'merge',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input1',
        label: 'Input 1',
        multiple: true,
        portType: '',
        side: 'left',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input2',
        label: 'Input 2',
        multiple: true,
        portType: '',
        side: 'left',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input3',
        label: 'Input 3',
        multiple: true,
        portType: '',
        side: 'left',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input4',
        label: 'Input 4',
        multiple: true,
        portType: '',
        side: 'left',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input5',
        label: 'Input 5',
        multiple: true,
        portType: '',
        side: 'left',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Merge',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: 'right',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Combines up to five input ports into a single output payload.',
    usage:
      'Connect any of Input 1..5. Plain objects are shallow-merged in input1..input5 order and non-object payloads are preserved under their originating port key.',
  },
  {
    commands: [],
    fields: ['description', 'metadata', 'status', 'source', 'timestamp', 'internalNodeLibraryId', 'failureMitigation', 'retryCount'],
    group: 'Data',
    id: 'metadata',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Metadata',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Expose input, runtime properties, and node metadata for downstream steps.',
    usage: 'Use Metadata to surface the current node input, runtime properties, and identity for downstream worker-owned steps.',
  },
  {
    commands: [],
    fields: ['description', 'internalNodeLibraryId', 'status', 'source', 'timestamp', 'failureMitigation', 'retryCount'],
    group: 'Flow Control',
    id: 'if-else',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'If/Else',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'true',
        label: 'true',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'false',
        label: 'false',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Execute branch code and activate exactly one of the true/false outputs.',
    usage:
      'Write branch logic in the code editor, return either `{ true: ... }` or `{ false: ... }`, and the worker will activate exactly one branch.',
  },
  {
    commands: [],
    fields: ['loopItems', 'description', 'internalNodeLibraryId', 'status', 'source', 'timestamp', 'failureMitigation', 'retryCount'],
    group: 'Flow Control',
    id: 'loop-over-items',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: 'left',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Loop Over Items',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'done',
        label: 'done',
        multiple: true,
        portType: '',
        side: 'right',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'loop',
        label: 'loop',
        multiple: true,
        portType: '',
        side: 'right',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Resolves a collection from Loop Items and chooses one branch in a single-pass execution.',
    usage: 'Set Loop Items to a variable token or path. Non-empty collections route to `loop`; empty collections route to `done`.',
  },
  {
    commands: [],
    fields: ['findValue', 'replaceWith', 'description', 'internalNodeLibraryId', 'status', 'source', 'timestamp', 'failureMitigation', 'retryCount'],
    group: 'Flow Control',
    id: 'replace-me',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: 'left',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Replace Me',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: 'right',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Recursively replaces string values in payload values only.',
    usage: 'Set Find Value and Replace With. Replacement is case-sensitive and global in string values; object keys are untouched.',
  },
  {
    commands: [],
    fields: ['description', 'internalNodeLibraryId', 'status', 'source', 'timestamp', 'failureMitigation', 'retryCount'],
    group: 'Flow Control',
    id: 'respond-end',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: false,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: false,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Respond End',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Finish execution and emit the terminal payload exactly as output.',
    usage: 'Use Respond / End as the terminal node to return the final upstream payload without workflow/node wrapper metadata.',
  },
  {
    commands: [],
    fields: [
      'forwardSessionLogs',
      'variables',
      'prompt',
      'description',
      'triggerSource',
      'webhookMethod',
      'webhookTestUrl',
      'webhookPublishedUrl',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Flow Control',
    id: 'start',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Start',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Emits workflow bootstrap context, runtime variables, prompt guidance, and workflow metadata.',
    usage: 'Use Start once per workflow to seed variables/prompt context and begin downstream execution.',
  },
  {
    commands: [],
    fields: ['description', 'mode', 'status', 'source', 'timestamp', 'internalNodeLibraryId', 'failureMitigation', 'retryCount'],
    group: 'Flow Control',
    id: 'stop-error',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Stop Error',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Explicitly stop or fail the workflow from a worker-owned control node.',
    usage: 'Choose stop to halt execution cleanly or error to fail the workflow with a deterministic worker result.',
  },
  {
    commands: [],
    fields: ['description', 'unit', 'time', 'internalNodeLibraryId', 'status', 'source', 'timestamp', 'failureMitigation', 'retryCount'],
    group: 'Flow Control',
    id: 'wait',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: 'left',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Wait',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: 'right',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Pause workflow execution for the configured duration in the worker runtime.',
    usage: 'Set a duration and unit to delay downstream execution without involving a backend service.',
  },
  {
    commands: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    fields: [
      'description',
      'executionSource',
      'workflowId',
      'workflowName',
      'workflowScope',
      'parameters',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Flow Nodes',
    id: 'execute-workflow',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
    ],
    name: 'Execute Workflow',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
    ],
    summary:
      'Worker-owned execution node for published workflows. It accepts a selected workflow or a workflow id from input and returns terminal output plus the editor link.',
    usage:
      'Use Selected Workflow when you want a fixed published target. Use Input Workflow ID when a previous node created or published the workflow during the current run.',
  },
  {
    commands: [],
    fields: [
      'description',
      'action',
      'reason',
      'chatId',
      'message',
      'topK',
      'subjectIds',
      'postIds',
      'tagSlugs',
      'actionInput',
      'resultsById',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Giga Action Nodes',
    id: 'run-category-action',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Category',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Executes a selected category action with workflow runtime context.',
    usage: 'Choose an action and pass backend arguments in actionInput JSON.',
  },
  {
    commands: [],
    fields: [
      'description',
      'action',
      'reason',
      'chatId',
      'message',
      'topK',
      'subjectIds',
      'postIds',
      'tagSlugs',
      'actionInput',
      'resultsById',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Giga Action Nodes',
    id: 'run-channel-action',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Channel',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Executes a selected channel action with workflow runtime context.',
    usage: 'Choose an action and pass backend arguments in actionInput JSON.',
  },
  {
    commands: [],
    fields: [
      'description',
      'action',
      'reason',
      'chatId',
      'message',
      'topK',
      'subjectIds',
      'postIds',
      'tagSlugs',
      'actionInput',
      'resultsById',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Giga Action Nodes',
    id: 'run-chat-action',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Chat',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Executes a selected chat/retrieval action with workflow runtime context.',
    usage: 'Choose a chat action and pass backend arguments in actionInput JSON.',
  },
  {
    commands: [],
    fields: [
      'description',
      'action',
      'reason',
      'chatId',
      'message',
      'topK',
      'subjectIds',
      'postIds',
      'tagSlugs',
      'actionInput',
      'resultsById',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Giga Action Nodes',
    id: 'run-post-action',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Post',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Executes a selected post action with workflow runtime context.',
    usage: 'Choose an action and pass backend arguments in actionInput JSON.',
  },
  {
    commands: [],
    fields: [
      'description',
      'action',
      'reason',
      'chatId',
      'message',
      'topK',
      'subjectIds',
      'postIds',
      'tagSlugs',
      'actionInput',
      'resultsById',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Giga Action Nodes',
    id: 'run-subject-action',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Subject',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Executes a selected subject action with workflow runtime context.',
    usage: 'Choose an action and pass backend arguments in actionInput JSON. Use the SERP node path for visible reference sync workflows.',
  },
  {
    commands: [],
    fields: [
      'description',
      'action',
      'reason',
      'chatId',
      'message',
      'topK',
      'subjectIds',
      'postIds',
      'tagSlugs',
      'actionInput',
      'resultsById',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Giga Action Nodes',
    id: 'run-user-tree-action',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'User Tree',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Executes the user-tree read action with workflow runtime context.',
    usage: 'Use fetch_user_tree to inspect the current channel/category/subject/post tree.',
  },
  {
    commands: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [
          'run-channel-action',
          'run-category-action',
          'run-subject-action',
          'run-post-action',
          'run-user-tree-action',
          'run-chat-action',
        ],
        key: 'actions',
        label: 'Actions',
        multiple: true,
        portType: 'bi-directional',
        side: 'bottom',
      },
    ],
    fields: [
      'description',
      'toolName',
      'toolDescription',
      'broadcastModelId',
      'allowedActions',
      'strictConnectionCheck',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Giga AI Nodes',
    id: 'action-router',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
    ],
    name: 'Action Router',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
    ],
    summary: 'Governor-facing tool node that broadcasts one planned backend action into one grouped Action node.',
    usage:
      'Connect this node to AI Governor on Command and connect exactly one grouped Action node on Actions. The planner selects this router as a tool, then sends one action plus actionInput through it.',
  },
  {
    commands: [],
    fields: [
      'description',
      'confirmationPolicy',
      'mutatingActions',
      'workflowOutputActions',
      'validationPolicy',
      'emptyPlanBehavior',
      'confirmedWithoutPendingBehavior',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Giga AI Nodes',
    id: 'chat-plan-policy',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
    ],
    name: 'Planner',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'confirmation_required',
        label: 'Confirmation Required',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'execute_now',
        label: 'Execute Now',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'execute_confirmed',
        label: 'Execute Confirmed',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'no_pending',
        label: 'No Pending',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'planning_failure',
        label: 'Planning Failure',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
    ],
    summary: 'Deterministic policy node for confirmation routing, workflow-output routing, and planning failures.',
    usage: 'Feed AI Governor plan output, Current Chat pending state, Chat Analysis flags, and optional workflow validation into Planner.',
  },
  {
    commands: [],
    fields: [
      'description',
      'analysisKinds',
      'confirmationPhrases',
      'confirmationRegexOverride',
      'workflowEntityTerms',
      'workflowVerbTerms',
      'workflowRequestRegexOverride',
      'followupReferenceTerms',
      'followupVerbTerms',
      'requireLastWorkflowState',
      'workflowFollowupRegexOverride',
      'mutationVerbs',
      'mutationTargets',
      'mutationRegexOverride',
      'referenceTerms',
      'referenceTargets',
      'referenceRegexOverride',
      'explanationTerms',
      'explanationRegexOverride',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Giga AI Nodes',
    id: 'text-analysis',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
    ],
    name: 'Text Analysis',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
    ],
    summary: 'Worker-owned node that turns text and workflow state into reusable intent flags.',
    usage:
      'Place after Current Chat, then enable only the rule families you want. Use structured term lists by default and add a regex override only when you need tighter matching.',
  },
  {
    commands: [],
    fields: [
      'description',
      'cypherInputSource',
      'cypher',
      'targetWorkflowName',
      'executable',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Giga AI Nodes',
    id: 'validate-workflow-cypher',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
    ],
    name: 'Validate Workflow Cypher',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
    ],
    summary: 'Worker-owned node that compiles Workflow Cypher without creating or updating a workflow.',
    usage: 'Choose the Cypher source explicitly, then feed the validation result into Planner before workflow mutations.',
  },
  {
    commands: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: ['openai', 'claude', 'gemini', 'groq', 'deepseek', 'perplexity', 'mistral'],
        key: 'llm',
        label: 'LLM',
        multiple: true,
        portType: 'bi-directional',
        side: 'bottom',
      },
    ],
    fields: [
      'description',
      'operation',
      'saveMode',
      'definitionSource',
      'publishAfterSave',
      'workflowIdSource',
      'scope',
      'organizationId',
      'workflowId',
      'workflowName',
      'workflowDescription',
      'workflowPrompt',
      'cypher',
      'executable',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Giga AI Nodes',
    id: 'workflow',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
    ],
    name: 'Workflow',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
    ],
    summary:
      'Worker-owned workflow management node. Use it to list, fetch, save, publish, and delete workflows, or to create a workflow from AI through a connected LLM node.',
    usage:
      'Configure the operation first. Save supports either Cypher or AI. When using AI, connect one LLM node on cmd:llm and provide a workflow prompt that describes what the workflow should do.',
  },
  {
    commands: [],
    fields: ['description', 'internalNodeLibraryId', 'status', 'source', 'timestamp', 'failureMitigation', 'retryCount'],
    group: 'MCP Group',
    id: 'mcp-capabilities',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: 'left',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'MCP Capabilities',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: 'right',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Run MCP initialize plus tools/list against the selected MCP credential.',
    usage: 'Select an MCP credential and emit discovered tools, capabilities, serverInfo, and protocolVersion.',
  },
  {
    commands: [],
    fields: [
      'description',
      'outputContract',
      'capabilityQuery',
      'forwardNonMcpWork',
      'loopNonMcpWork',
      'maxLoopPasses',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'MCP Group',
    id: 'mcp-runtime',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: 'left',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'MCP Execute',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: 'right',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'loop',
        label: 'loop',
        multiple: true,
        portType: '',
        side: 'right',
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'List real MCP tools and call a selected tool through the selected MCP credential.',
    usage:
      'Select an MCP credential, then pass a tool call as flat payload, `payload` envelope, connected workflow input bucket, or inspector `current` payload.',
  },
  {
    commands: [],
    fields: [
      'description',
      'model',
      'prompt',
      'temperature',
      'status',
      'source',
      'timestamp',
      'internalNodeLibraryId',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Other',
    id: 'analyze-text-with-model',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Analyze Text With Model',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Runs model analysis against provided text payload.',
    usage: 'Pass source text, prompt, and model settings to obtain classified/summarized outputs.',
  },
  {
    commands: [
      {
        acceptedSourceGroups: ['AI Models'],
        acceptedSourceModelIds: ['openai', 'claude', 'gemini', 'groq', 'deepseek', 'perplexity', 'mistral'],
        key: 'llm',
        label: 'LLM',
        multiple: true,
        portType: 'bi-directional',
        side: 'bottom',
      },
    ],
    fields: [
      'description',
      'format',
      'value',
      'useAiFormatting',
      'modelId',
      'aiPrompt',
      'status',
      'source',
      'timestamp',
      'internalNodeLibraryId',
      'failureMitigation',
      'retryCount',
      'forwardSessionLogs',
    ],
    group: 'Other',
    id: 'output-format',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Output Format',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Format output as JSON, Markdown, raw text, or table data with optional connected-LLM refinement.',
    usage:
      'Choose a format, optionally connect an LLM node, and let the worker either format deterministically or hand the format request to the connected model.',
  },
  {
    commands: [],
    fields: [
      'description',
      'query',
      'max_results',
      'location',
      'language',
      'internalNodeLibraryId',
      'status',
      'source',
      'timestamp',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Other',
    id: 'serp-search',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Serp Search',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Runs server-side SERP lookup and returns normalized web results.',
    usage: 'Set query and optional max_results/location/language to collect external references.',
  },
  {
    commands: [],
    fields: [
      'description',
      'queryKey',
      'queryText',
      'variables',
      'headers',
      'status',
      'source',
      'timestamp',
      'internalNodeLibraryId',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Server Actions',
    id: 'graphql',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Graphql',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Execute GraphQL requests locally using workflow runtime settings.',
    usage: 'Provide a query, variables, and optional headers to execute GraphQL requests directly from the worker using workflow settings.',
  },
  {
    commands: [],
    fields: [
      'description',
      'method',
      'url',
      'bodyMode',
      'jsonBody',
      'formBody',
      'files',
      'headers',
      'status',
      'source',
      'timestamp',
      'internalNodeLibraryId',
      'failureMitigation',
      'retryCount',
    ],
    group: 'Server Actions',
    id: 'http-request',
    inputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'input',
        label: 'input',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    name: 'Http Request',
    outputs: [
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'output',
        label: 'output',
        multiple: true,
        portType: '',
        side: null,
      },
      {
        acceptedSourceGroups: [],
        acceptedSourceModelIds: [],
        key: 'command',
        label: 'Command',
        multiple: true,
        portType: 'bi-directional',
        side: 'top',
      },
    ],
    summary: 'Call HTTP endpoints locally using workflow runtime settings and optional files.',
    usage: 'Configure method, URL, headers, and body mode to issue HTTP requests directly from the worker runtime.',
  },
];
