import type { GraphqlOperationContract, RoleGateContract } from '@giga/shared/types/contracts/integration-contract.types';

const roles: RoleGateContract[] = [
  { actor: 'User', canInvoke: true, constraints: ['Session token required', 'Scope checks enforced per resolver.'] },
  { actor: 'Root User', canInvoke: true, constraints: ['Root-level policy checks apply on elevated operations.'] },
  { actor: 'Super Admin', canInvoke: true, constraints: ['Global/org checks and plan-policy checks apply.'] },
];

const sourcePaths = [
  'packages/apps/general/src/services/graphql/resolvers/integration/chat.resolver.ts',
  'packages/apps/general/src/services/graphql/resolvers/integration/workflow.resolver.ts',
  'packages/apps/general/src/services/graphql/resolvers/integration/mcp.resolver.ts',
];

const row = (
  operationName: string,
  kind: 'QUERY' | 'MUTATION',
  inputType: string,
  outputType: string,
  description: string,
  required: string[],
  optional: string[],
  notes: string[],
): GraphqlOperationContract => ({
  packageName: '@giga/general',
  operationName,
  kind,
  inputType,
  outputType,
  description,
  parameters: [
    ...required.map((name) => ({ name, type: 'field', required: true, description: 'Required by resolver contract.' })),
    ...optional.map((name) => ({ name, type: 'field', required: false, description: 'Optional by resolver contract.' })),
  ],
  combinations: [{ name: 'default', required, optional, constraints: ['Input object must satisfy resolver-specific validation.'] }],
  roleGates: roles,
  sourcePaths,
  notes,
});

export const GRAPHQL_CONTRACTS: GraphqlOperationContract[] = [
  row(
    'chatQuery',
    'MUTATION',
    'ChatQueryInput',
    'ChatQueryPayload',
    'Primary chat execution mutation.',
    ['input.message'],
    ['input.chat_mode', 'input.agent_id', 'input.workflow_id', 'input.swarm_id'],
    ['Chat mode routing: DEFAULT, AGENT, WORKFLOW, SWARM.'],
  ),
  row(
    'chatSend',
    'MUTATION',
    'ChatQueryInput',
    'ChatQueryPayload',
    'Chat alias mutation using same engine as chatQuery.',
    ['input.message'],
    ['input.chat_mode', 'input.agent_id', 'input.workflow_id'],
    ['Maintains chatQuery behavior parity.'],
  ),
  row(
    'chatConfirm',
    'MUTATION',
    'ChatConfirmInput',
    'ChatQueryPayload',
    'Confirms pending action plans from assistant output.',
    ['input.chat_id', 'input.confirmation_id'],
    ['input.message'],
    ['Confirmation flow is guarded by pending plan metadata.'],
  ),
  row(
    'chatSession',
    'QUERY',
    'ChatSessionInput',
    'ChatSessionPayload',
    'Reads one chat session payload and metadata.',
    ['input.chat_id'],
    [],
    ['Used to restore current UI chat context.'],
  ),
  row(
    'chatSessions',
    'QUERY',
    'ChatSessionsInput',
    'ChatSessionsPayload',
    'Reads paginated chat list for current user scope.',
    [],
    ['input.first', 'input.offset', 'input.scope_type'],
    ['Returns list + pagination payload.'],
  ),
  row(
    'chatMessages',
    'QUERY',
    'ChatMessagesInput',
    'ChatMessagesPayload',
    'Reads paginated messages for a chat.',
    ['input.chat_id'],
    ['input.first', 'input.offset'],
    ['Supports UI chat replay and history pages.'],
  ),
  row(
    'agentRetrieve',
    'QUERY',
    'AgentRetrieveInput',
    'AgentRetrievePayload',
    'Retrieves AI context chunks for a chat request.',
    ['input.message'],
    ['input.subject_ids', 'input.post_ids', 'input.top_k'],
    ['Used by AI helper flows for preview/debug.'],
  ),
  row(
    'agentExecute',
    'MUTATION',
    'AgentExecuteInput',
    'AgentExecutePayload',
    'Executes AI helper with tools for provided message.',
    ['input.message'],
    ['input.chat_id', 'input.agent_id', 'input.workflow_id'],
    ['Bridges planner + action execution pipeline.'],
  ),
  row(
    'agentIngestPost',
    'MUTATION',
    'AgentIngestPostInput',
    'IngestPayload',
    'Queues post ingestion as a background process and returns immediate job handle.',
    ['input.post_id'],
    ['input.replace_existing', 'input.chunk_size', 'input.chunk_overlap'],
    ['Async ingestion returns accepted + ingestion_job_id + process_id; progress/logs stream over socket events.'],
  ),
  row(
    'agentIngestAttachment',
    'MUTATION',
    'AgentIngestAttachmentInput',
    'IngestPayload',
    'Queues attachment ingestion as a background process and returns immediate job handle.',
    ['input.attachment_id'],
    ['input.replace_existing', 'input.chunk_size', 'input.chunk_overlap'],
    ['Async ingestion returns accepted + ingestion_job_id + process_id; progress/logs stream over socket events.'],
  ),
  row(
    'workflowCatalogRecords',
    'QUERY',
    'WorkflowCatalogRecordsInput',
    'WorkflowCatalogRecordsPayload',
    'Lists catalog workflows for selector and attachment UIs.',
    [],
    ['input.search', 'input.scope', 'input.organizationIds', 'input.first', 'input.offset'],
    ['Used by workflow picker in frontend.'],
  ),
  row(
    'workflowExecutions',
    'QUERY',
    'workflowId + pagination args',
    '[WorkflowExecutionPayload!]',
    'Lists workflow execution runs and statuses.',
    ['workflowId', 'scope'],
    ['first', 'offset', 'organizationId'],
    ['Backs workflow execution history panes.'],
  ),
  row(
    'workflowExecute',
    'MUTATION',
    'WorkflowExecutionInput',
    'WorkflowExecutionPayload',
    'Executes workflow from chat or explicit UI request.',
    ['input.workflow'],
    ['input.workflowId', 'input.organizationId', 'input.chatId'],
    ['Runtime queue and plan-policy checks enforced.'],
  ),
  row(
    'workflowCreateUserNode',
    'MUTATION',
    'WorkflowUserNodeInput',
    'WorkflowUserNodePayload',
    'Creates scoped workflow node package.',
    ['input.name', 'input.sourceFiles'],
    ['input.scopeType', 'input.organizationId'],
    ['Node designer permissions required.'],
  ),
  row(
    'workflowUpdateUserNode',
    'MUTATION',
    'id + WorkflowUserNodeInput',
    'WorkflowUserNodePayload',
    'Updates scoped workflow node package.',
    ['id'],
    ['input'],
    ['Node designer update permission required.'],
  ),
  row(
    'workflowDeleteUserNode',
    'MUTATION',
    'id',
    'WorkflowDeleteUserNodePayload',
    'Deletes scoped workflow node package.',
    ['id'],
    [],
    ['Node designer delete permission required.'],
  ),
  row(
    'workflowValidateNodePackage',
    'MUTATION',
    'WorkflowNodePackageInput',
    'WorkflowNodePackagePayload',
    'Validates node package archive before import.',
    ['input.packageBase64'],
    ['input.scopeType', 'input.organizationId'],
    ['Validation error details returned in payload.'],
  ),
  row(
    'mcpTools',
    'QUERY',
    'none',
    '[JSON!]',
    'Lists MCP tools proxied through GraphQL resolver.',
    [],
    [],
    ['Tool metadata is sourced from @giga/mcp runtime registry.'],
  ),
  row(
    'mcpExecuteTool',
    'MUTATION',
    'McpToolExecutionInput',
    'JSON',
    'Executes selected MCP tool through GraphQL proxy.',
    ['input.name'],
    ['input.args'],
    ['Resolver access matrix and audit logging enforced.'],
  ),
];

export const NO_GRAPHQL_SURFACE_REASON = '';
